apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: emqx-serrrrr
  namespace: default
spec:
  chart: https://papandadj.github.io/charts/emqx-server-0.1.0.tgz
  targetNamespace: default
  set:
    nodeSelector: 
      k3s.io/hostname: envy